#!/bin/bash

# Create a directory for the cloned repositories
mkdir -p daggerverse_repos
cd daggerverse_repos

# Function to clone a repo
clone_repo() {
   local repo_url="$1"
   local repo_name=$(basename "$repo_url" .git)

   if [ ! -d "$repo_name" ]; then
       git clone --depth 1 "$repo_url" || echo failed
   else
       echo "Repository $repo_name already exists. Skipping..."
   fi
}

# Clone repositories
clone_repo https://github.com/shykes/daggerverse
clone_repo https://github.com/dagger/dagger
clone_repo https://github.com/purpleclay/daggerverse
clone_repo https://github.com/scottames/daggerverse
clone_repo https://github.com/levlaz/daggerverse
clone_repo https://github.com/seungyeop-lee/daggerverse
clone_repo https://github.com/camptocamp/daggerverse
clone_repo https://github.com/pjmagee/dagger-apache-avro-tools
clone_repo https://github.com/matipan/daggerverse
clone_repo https://github.com/puzzle/dagger-module-vault-kv
clone_repo https://github.com/helderco/daggerverse
clone_repo https://github.com/kpenfound/dagger-modules
clone_repo https://github.com/vito/daggerverse
clone_repo https://github.com/jedevc/shykes-daggerverse
clone_repo https://github.com/sagikazarmark/daggerverse
clone_repo https://github.com/swanncroiset/daggerverse
clone_repo https://github.com/chainloop-dev/chainloop
clone_repo https://github.com/cloudnative-pg/daggerverse
clone_repo https://github.com/KGB33/daggerverse
clone_repo https://github.com/csatib02/openmeter
clone_repo https://github.com/staticaland/daggerverse
clone_repo https://github.com/marcosnils/daggerverse
clone_repo https://github.com/fluent-ci-templates/rust-pipeline
clone_repo https://github.com/fluent-ci-templates/deno-pipeline
clone_repo https://github.com/TomChv/dagger
clone_repo https://github.com/dciangot/kaggle-dagger
clone_repo https://github.com/dannyhorvath0/dagger-modules
clone_repo https://github.com/jpadams/gcp-for-dagger
clone_repo https://github.com/prometheus/client_golang
clone_repo https://github.com/felipecruz91/daggerverse
clone_repo https://github.com/pjmagee/dagger-heroes-decode
clone_repo https://github.com/TruStacks/daggerverse
clone_repo https://github.com/peterj/dagger-modules
clone_repo https://github.com/samalba/dagger-modules
clone_repo https://github.com/matipan/publish-test
clone_repo https://github.com/mycroft/go-dagger-ci
clone_repo https://github.com/by-nelson/daggerverse
clone_repo https://github.com/Prashant-Bhapkar/demo1
clone_repo https://github.com/EmmS21/financialadvisor
clone_repo https://github.com/francoissharpe/daggerverse
clone_repo https://github.com/msthtrifork/sec-scan
clone_repo https://github.com/Prashant-Bhapkar/demo
clone_repo https://github.com/mgreau/daggerverse
clone_repo https://github.com/sipsma/dagger-test-modules
clone_repo https://github.com/sneelco/dagger-pyecho
clone_repo https://github.com/EmmS21/daggerverse
clone_repo https://github.com/jpadams/daggerverse
clone_repo https://github.com/daggerverse/dagger-azure
clone_repo https://github.com/sarahethompson/daggerverse
clone_repo https://github.com/fluent-ci-templates/sonar-pipeline
clone_repo https://github.com/denhamparry/daggerverse
clone_repo https://github.com/ernesto27/daggerverse
clone_repo https://github.com/fluent-ci-templates/trivy-pipeline
clone_repo https://github.com/maxberger/daggerverse
clone_repo https://github.com/Dudesons/daggerverse
clone_repo https://github.com/felipecruz91/daggerverse
clone_repo https://github.com/z4ce/snyk-dagger
clone_repo https://github.com/marcosnils/daggerverse-1
clone_repo https://github.com/anthonybrice/daggerverse
clone_repo https://github.com/llorenzinho/dagger-package-repository
clone_repo https://github.com/chrira/dagger-module-java-sdk-update
clone_repo https://github.com/Transmitt0r/daggerverse
clone_repo https://github.com/d3rp3tt3/daggerverse
clone_repo https://github.com/mustafayildirim/daggerverse
clone_repo https://github.com/vito/daggerverse
clone_repo https://github.com/slumbering/daggerverse
clone_repo https://github.com/fluent-ci-templates/railway-pipeline
clone_repo https://github.com/fluent-ci-templates/supabase-pipeline
clone_repo https://github.com/fluent-ci-templates/gitleaks-pipeline
clone_repo https://github.com/dlorenc/wheel-builder
clone_repo https://github.com/fluent-ci-templates/grype-pipeline
clone_repo https://github.com/fluent-ci-templates/syft-pipeline
clone_repo https://github.com/fluent-ci-templates/firebase-pipeline
clone_repo https://github.com/jedevc/daggerverse
clone_repo https://github.com/fluent-ci-templates/bun-pipeline
clone_repo https://github.com/fluent-ci-templates/shuttle-pipeline
clone_repo https://github.com/fluent-ci-templates/chromatic-pipeline
clone_repo https://github.com/fluent-ci-templates/wasmer-pipeline
clone_repo https://github.com/dagger/dagger
clone_repo https://github.com/Excoriate/daggerverse
clone_repo https://github.com/aweris/daggerverse
clone_repo https://github.com/kgb33/daggerverse
clone_repo https://github.com/gerhard/daggerverse
clone_repo https://github.com/jpadams/testgit
clone_repo https://github.com/tsirysndr/daggerverse
clone_repo https://github.com/dariusj1/daggerverse
clone_repo https://github.com/launchdarkly/ld-find-code-refs
clone_repo https://github.com/vito/bass
clone_repo https://github.com/jpadams/cullen
clone_repo https://github.com/jpadams/milan-test
clone_repo https://github.com/jpadams/example-go-build-container
clone_repo https://github.com/jpadams/bar
clone_repo https://github.com/adore-me/daggerverse
clone_repo https://github.com/Wompipomp/daggerverse
clone_repo https://github.com/cloudsmith-io/daggerverse
clone_repo https://github.com/jmiller-cs/daggerverse
clone_repo https://github.com/vikram-dagger/daggerverse
clone_repo https://github.com/lukemarsden/dagger-aws
clone_repo https://github.com/lukemarsden/dagger-gcp
clone_repo https://github.com/lukemarsden/dagger-snyk
clone_repo https://github.com/lukemarsden/dagger-grype
clone_repo https://github.com/helixml/dagger
clone_repo https://github.com/lukemarsden/dagger-ghcr-demo
clone_repo https://github.com/quartz-technology/daggerverse
clone_repo https://github.com/mjb141/daggerverse
clone_repo https://github.com/pck/daggerverse
clone_repo https://github.com/joebui/dagger-module-ci-cd
clone_repo https://github.com/SpokaneTech/SpokaneTech_Py
clone_repo https://github.com/BondMachineHQ/BMBuildkit-dagger
clone_repo https://github.com/shykes/core
clone_repo https://github.com/d3rp3tt3/daggerverse
clone_repo https://github.com/vbehar/daggerverse
clone_repo https://github.com/jcsirot/daggerverse
clone_repo https://github.com/marxarelli/daggerverse
clone_repo https://github.com/grouville/daggerverse
clone_repo https://github.com/aluzzardi/daggerverse
clone_repo https://github.com/samalba/aluzzardi-daggerverse
clone_repo https://github.com/wingyplus/daggerverse
clone_repo https://github.com/fluent-ci-templates/gleam-pipeline
clone_repo https://github.com/grouville/daggerverse-tom
clone_repo https://github.com/fluent-ci-templates/android-pipeline
clone_repo https://github.com/jumppad-labs/daggerverse
clone_repo https://github.com/fluent-ci-templates/fastlane-pipeline
clone_repo https://github.com/nicholasjackson/demo-dagger-vault
clone_repo https://github.com/fluent-ci-templates/drizzlekit-pipeline
clone_repo https://github.com/sipsma/daggerverse
clone_repo https://github.com/fluent-ci-templates/dotnet-pipeline
clone_repo https://github.com/fluent-ci-templates/snyk-pipeline
clone_repo https://github.com/fluent-ci-templates/spin-pipeline
clone_repo https://github.com/fluent-ci-templates/github-pipeline
clone_repo https://github.com/samalba/inline-python-mod
clone_repo https://github.com/grouville/daggerverse
clone_repo https://github.com/jpadams/semgrep-dagger-module
clone_repo https://github.com/helixml/runner
clone_repo https://github.com/quartz-technology/daggerverse
clone_repo https://github.com/fluent-ci-templates/buf-pipeline
clone_repo https://github.com/fluent-ci-templates/elixir-pipeline
clone_repo https://github.com/fluent-ci-templates/atlas-pipeline
clone_repo https://github.com/fluent-ci-templates/prisma-pipeline
clone_repo https://github.com/cirocosta/daggerverse
clone_repo https://github.com/slimtoolkit/daggerverse
clone_repo https://github.com/aweris/gale
clone_repo https://github.com/matipan/daggerverse
clone_repo https://github.com/ibuildthecloud/daggerverse
clone_repo https://github.com/kpenfound/testcontainers-java-repro
clone_repo https://github.com/TomChv/daggerverse
clone_repo https://github.com/shykes/dagger
clone_repo https://github.com/ginjiruu/moodle_plugin_ci
clone_repo https://github.com/adrienbrault/hf-gguf-to-ollama
clone_repo https://github.com/camptocamp/setup-dagger
clone_repo https://github.com/skycaptain/daggerverse
clone_repo https://github.com/aiseei/hf-gguf-to-ollama
clone_repo https://github.com/Smana/daggerverse
clone_repo https://github.com/anthonybrice/timpkg
clone_repo https://github.com/jalvarezit/daggerverse
clone_repo https://github.com/bmwinstead/dagger-test
clone_repo https://github.com/salaboy/example-voting-app
clone_repo https://github.com/jumppad-labs/daggerverse
clone_repo https://github.com/Mjb141/dag-kics
clone_repo https://github.com/carnage/dagger-php-module
clone_repo https://github.com/fluentci-io/daggerverse
clone_repo https://github.com/aweris/demo-devconf-cz-2024
clone_repo https://github.com/aweris/tt
clone_repo https://github.com/wingyplus/dagger
clone_repo https://github.com/MikaelElkiaer/daggerverse
clone_repo https://github.com/developer-guy/excoriate-daggerverse
clone_repo https://github.com/Clarity-Innovation-Technology-Inc/daggerverse
clone_repo https://github.com/RajaPoseidon/openmeter
clone_repo https://github.com/Digio-Campus/potato
clone_repo https://github.com/JuanValeraDev/potato
clone_repo https://github.com/Yedidyar/remult-cli
clone_repo https://github.com/kpenfound/greetings-api
clone_repo https://github.com/rropen/dagger-snyk
clone_repo https://github.com/chainloop-dev/integration-demo
clone_repo https://github.com/Clarity-Innovation-Technology-Inc/daggerverse
clone_repo https://github.com/techdecline/terraform-module
clone_repo https://github.com/steve-nzr/daggerverse
clone_repo https://github.com/crjm/dagger-modules
clone_repo https://github.com/nicholasjackson/daggerverse
clone_repo https://github.com/okteto/dagger-module
clone_repo https://github.com/openmeterio/openmeter
clone_repo https://github.com/cullenmcdermott/daggerverse-jumppad-labs
clone_repo https://github.com/bzp2010/openmeter
clone_repo https://github.com/prometheus/client_golang
clone_repo https://github.com/franela/pocketci
clone_repo https://github.com/tuananh/daggerverse
clone_repo https://github.com/EmmS21/DebtRepayment
clone_repo https://github.com/interTwin-eu/interLink

echo "All repositories have been cloned or updated."